# Generated by Django 5.0.6 on 2024-09-16 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wales', '0004_postcodedata_normalized_postcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='county',
            name='name',
            field=models.TextField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='district',
            name='name',
            field=models.TextField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='ward',
            name='name',
            field=models.TextField(db_index=True, max_length=100),
        ),
    ]
