# Generated by Django 5.0.6 on 2024-09-13 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('England', '0002_postcodedata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postcodedata',
            name='average_income',
        ),
        migrations.RemoveField(
            model_name='postcodedata',
            name='in_use',
        ),
        migrations.RemoveField(
            model_name='postcodedata',
            name='introduced',
        ),
        migrations.RemoveField(
            model_name='postcodedata',
            name='last_updated',
        ),
        migrations.RemoveField(
            model_name='postcodedata',
            name='national_park',
        ),
        migrations.RemoveField(
            model_name='postcodedata',
            name='terminated',
        ),
        migrations.RemoveField(
            model_name='postcodedata',
            name='travel_to_work_area',
        ),
        migrations.RemoveField(
            model_name='postcodedata',
            name='user_type',
        ),
    ]
