# Generated by Django 5.0.6 on 2024-09-17 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Scotland", "0005_alter_district_name_alter_ward_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="postcodedata",
            name="Census_output_area",
        ),
        migrations.RemoveField(
            model_name="postcodedata",
            name="Census_output_area_2021",
        ),
        migrations.RemoveField(
            model_name="postcodedata",
            name="Country",
        ),
    ]
