# Generated by Django 5.0.6 on 2024-09-17 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Scotland", "0006_remove_postcodedata_census_output_area_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="postcodedata",
            name="Travel_To_Work_Area",
        ),
    ]
