# Generated by Django 5.0.6 on 2024-09-14 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NorthernIreland', '0002_postcodedata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postcodedata',
            name='postcode',
            field=models.CharField(db_index=True, max_length=100),
        ),
    ]
