# Generated by Django 5.0.6 on 2024-09-17 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("NorthernIreland", "0005_alter_district_name_alter_ward_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="postcodedata",
            name="census_output_area",
        ),
        migrations.RemoveField(
            model_name="postcodedata",
            name="census_output_area_2021",
        ),
        migrations.RemoveField(
            model_name="postcodedata",
            name="country",
        ),
        migrations.RemoveField(
            model_name="postcodedata",
            name="introduced",
        ),
        migrations.RemoveField(
            model_name="postcodedata",
            name="last_updated",
        ),
        migrations.RemoveField(
            model_name="postcodedata",
            name="quality",
        ),
        migrations.RemoveField(
            model_name="postcodedata",
            name="travel_to_work_area",
        ),
        migrations.RemoveField(
            model_name="postcodedata",
            name="user_type",
        ),
    ]
